version: "1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: plannerbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres